CREATE TABLE USUARIO(
	id_usuario SERIAL PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	usuario VARCHAR(20) NOT NULL,
	contrasena VARCHAR(15) NOT NULL,
	administrador BOOLEAN NOT NULL,
	activo BOOLEAN NOT NULL
);

CREATE TABLE INVENTARIO(
	id_libro SERIAL PRIMARY KEY,
	nombre_libro VARCHAR (40) NOT NULL,
	descripcion VARCHAR(100) NOT NULL,
	precio DECIMAL NOT NULL,
	stock INT NOT NULL
);

CREATE TABLE PEDIDO(
	id_pedido SERIAL PRIMARY KEY,
	id_usuario INT NOT NULL,
	nombre_usuario VARCHAR(50) NOT NULL,
	id_libro INT NOT NULL,
	fecha_pedido TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE PEDIDO
ADD CONSTRAINT fk_pedido_usuario
FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario);

ALTER TABLE PEDIDO
ADD CONSTRAINT fk_pedido_inventario
FOREIGN KEY (id_libro) REFERENCES INVENTARIO(id_libro);

SELECT * FROM USUARIO
SELECT * FROM INVENTARIO
SELECT * FROM PEDIDO